name: macos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
 
    - name: Build
      run: dotnet build -c Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
