name: windows

on:
  push:
    branches: [ main ]

jobs:
  windows-latest:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
